version: "3.9"

services:
  terraform-repo-template:
    container_name: terraform-repo-template
    image: utkusarioglu/terraform-devcontainer:1.2.14
    volumes:
      - ..:/utkusarioglu-com/templates/terraform-repo-template
    environment:
      TZ: Etc/UTC 
